config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'blogs' => 'blog#index', as: 'blogs'
  get 'blogs/new' => 'blog#new', as: 'new_blog'
  get 'blogs/:id' => 'blog#show', as: 'blog' 
  root 'blog#index'
  post 'blogs' => 'blog#create'
  delete 'blogs/:id' => 'blog#destroy'
  patch 'blogs/:id' => 'blog#update'
  get 'blogs/:id/edit' => 'blog#edit', as: 'edit_blog'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, :content, presence: true
  validates :title, uniqueness: true, uniqueness: { case_sensitive: false }
  validates :title, length: { minimum: 4 }
  validates :content, length: { minimum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index
    @blogs = Blog.all
  end

  def show 
    @blog = Blog.find(params[:id])
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.create(blog_params)
    if @blog.valid? 
      redirect_to blogs_path
    end
  end

  def destroy
    @blog = Blog.find(params[:id])
    if @blog.destroy
      redirect_to blogs_path
    end
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    @blog.update(blog_params)
    if @blog.valid?
      redirect_to blogs_path
    end  
  end
  
private


  def blog_params
    params.require(:blog).permit(:title, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/views/blog/edit.html.erb
<h3>Edit your blog</h3>
<%= form_with model: @blog do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>
<br/>
  <%= form.label :content %>
  <%= form.text_field :content %>  
<br/>
  <%= form.submit 'Edit Blog' %>
<% end %>

app/views/blog/index.html.erb
<h1>Blog Titles</h1>
  <ul>
  <h3>Click on the title you would like to read more about</h3>
    <% @blogs.each do |blog| %>
    <li>
    
    <%= link_to blog.title, blog_path(blog) %>
    </li>
    <% end %>
  </ul>
  <br/>
  
  <p><%= link_to 'Create a New Blog', new_blog_path %></p>

app/views/blog/new.html.erb
<h3>Add a new blog</h3>
  <%= form_with model: @blog do |form| %>
    <%= form.label :title %>
    <%= form.text_field :title %>
  <br/>
    <%= form.label :content %>
    <%= form.text_field :content %>  
  <br/>
    <%= form.submit 'Add Blog' %>
  <% end %>
  <p><%= link_to 'Back to Home', blogs_path %></p>
    

app/views/blog/show.html.erb
<h3><%= @blog.title %></h3>
  <br/>
  <ul>
    <li>
      <%= @blog.content %>
    </li>
  </ul>
  <br/>
<p><%= link_to 'Back to Home', blogs_path %></p>
<%= link_to "Delete post", blog_path(@blog), data: {
                  'turbo_method': :delete,
                  'turbo_confirm': "Are you sure?"
                } %>
<p><%= link_to 'Edit this Blog', edit_blog_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FullstackDavidMichy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>